### ISSUE TITLE
Create a mapping table for qos_profiles

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/QualityOnDemand#1]

**Comment by T-sm** [comment]
The mapping table has been relocated to https://github.com/camaraproject/QualityOnDemand/blob/main/code/API_definitions/Notifications.md

**Comment by eric-murray** [comment]
THROUGHPUT_L should map to "Fastest available" - i.e. unrestricted by the mobile network operator. This is something of a "best effort" type definition, but reflects the fact that the peak throughput will be anyway limited by the radio channel over which the mobile operator has little control.

Mapping THROUGHPUT_S and THROUGHPUT_M to specific maximum throughput values is reasonable, and the current proposal of 10 and 30 Mb/s is also reasonable. But the problem here is these values might become outdated as networks evolve or may not fit with particular business cases. Values should be published as guidance for developers, but mechanism such as that proposed in Issue #7 is required so that the current throughput levels available to the target UE can be determined via the API itself.

**Comment by Marcin-Jarzab** [comment]
Issue has been discussed and current solution/proposal agreed on weekly 22.04.meeting.
