### ISSUE TITLE
API Versioning

### ISSUE THREAD

**Issue by chrishowell** [camaraproject/QualityOnDemand#179]
https://github.com/camaraproject/QualityOnDemand/blob/5f0002ef5d5b3bc0ec0ffb1fc7052316b6b52356/code/API_definitions/qod-api.yaml#L82

Is there a reason why the base path versioning is always using v0? these specs are not backwards compatible.

**Comment by hdamker** [comment]
The reason is that we are still in initial development / alpha status.

cf.: https://semver.org/#spec-item-4 ... "Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable."

I'm also not happy about the base path versioning v0. I had proposed in other places v0alpha1, v0alpha2 etc, but that was not understood and/or accepted.

If you have a proposal on improving the versioning in this initial phase you are welcome to do it in commonalities. See also this discussion we had a while ago: https://github.com/camaraproject/WorkingGroups/discussions/137
