### ISSUE TITLE
Add 400 - Bad Request for an invalid sessionId GET + DELETE /sessions/{sessionId}: 

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/QualityOnDemand#209]
**Problem description**
When attempting to access a session using the GET /sessions/{sessionId} endpoint, if you provide an invalid UUID as the sessionId parameter, the API will respond with an appropriate HTTP status code to indicate the error. However, it appears that there is currently no specific HTTP status code mentioned in the documentation for this scenario.

**Expected behavior**
The expected behavior for the scenario where an invalid UUID is provided as the sessionId parameter is to return an HTTP status code 400 - Bad Request. This status code signifies that the client's request was malformed or invalid, specifically in the context of an incorrect session ID format.

**Alternative solution**

```yaml
  /sessions/{sessionId}:
    get:
      responses:
         "400":
            $ref: "#/components/responses/Generic400"
```

**Additionally**

Same should be done for DELETE /sessios/{sessionId}

**Comment by patrice-conil** [comment]
Hi @maxl2287, 
I'm not a big fan of manually writing field-specific error messages because I prefer to delegate surface controls to my favorite JSON serializer/deserializer. 

If we have so many clients submitting invalid requests... why don't we provide them with a sandbox exposing a swagger UI to help them forge valid requests? And this sandbox would be a good starting point to help telecom operators validate implementation of their APIs. 
Another option should be to explain how to stop using curl and to import OAS spec in friendly tools that generate valid requests. 😄 

What do you think about?

**Comment by maxl2287** [comment]
> Hi @maxl2287, I'm not a big fan of manually writing field-specific error messages because I prefer to delegate surface controls to my favorite JSON serializer/deserializer.

I only used this "field-specific error message" just for this endpoint, because here it is only one possible parameter as a pathVariable, called "sessionId".
That's why I used here this specific field error message.

**Comment by maxl2287** [comment]
@patrice-conil understand,
I guess the easiest solution would be to stay with:

```yaml
        "400":
          $ref: "#/components/responses/Generic400"
```

**Comment by RandyLevensalor** [comment]
Should we add the 400 response as an incremental 0.9.x release?  It shouldn't break anything and adds better error handling.

**Comment by patrice-conil** [comment]
Hi @maxl2287,
I think we also need to add the 400 response in the delete.

**Comment by eric-murray** [comment]
Hi @maxl2287

I opened an [issue ](https://github.com/camaraproject/Commonalities/issues/31) in Commonalities proposing the adoption of RFC 7807 error responses to allow linking to more specific error documentation when the cause of the error may not be obvious. The proposal would require each API to define a full set of error responses within the API definition as "model error responses" which (taking into account the concerns of @patrice-conil) would be optional for an API provider to use.

Now in this case, where the error is due to straightforward non-compliance with the API OAS definition, then I agree with @patrice-conil that additional explanation of the error is not really required. But other errors may result from OAS compliant inputs and yet still be errors.

As you have raised this issue, and so are thinking about how API consumers use error responses, it would be useful to have your input in the issue in Commonalities.
