### ISSUE TITLE
Change duration of an active session

### ISSUE THREAD

**Issue by emil-cheung** [camaraproject/QualityOnDemand#220]
**Problem description**
Currently there is no mean to change the duration of an active session. However, there are use cases require extending the duration. A dedicated endpoint is proposed for this operation.

**Possible evolution**
N/A

**Alternative solution**
Use PATCH operation to change the duration.

**Additional context**
Originally, PATCH operation was proposed to change the duration. However, according the further discussion in issue #47 , a dedicated endpoint is preferred since it is straightforward to developers. This new issue is created to reflect the community discussion.

**Comment by ShutingQing** [comment]
Hi emil, how about discuss here [Include support for /PATCH sessions](https://github.com/camaraproject/QualityOnDemand/issues/47)? There will be more history infos.

**Comment by hdamker** [comment]
@ShutingQing 

> Hi emil, how about discuss here [Include support for /PATCH sessions](https://github.com/camaraproject/QualityOnDemand/issues/47)? There will be more history infos.

You are right, it is important to link back to the discussion in issue #47. The course of discussion there reduced the scope of a potential /PATCH operation step by step and ended with the conclusions:
* Duration can't be "patched" but should be an explicit endpoint (this issue here)
* NotificationAuthToken ... discussion postponed until new Event/Notification structure clarified (hopefully including handling of security)
All other points were already postponed earlier, incl. QoSProfile
