### ISSUE TITLE
Ensure secure handling of callback URL

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/QualityOnDemand#31]

**Comment by akoshunyadi** [comment]
To solve the issue about the unsecure callback I propose to use oauth2 instead (!) of the current api-key.
It means we would need new parameters (maybe in a substructure): Client-id, Client-secret and Access token URL.
Any comments?

**Comment by jlurien** [comment]
There is an [open issue](https://github.com/camaraproject/WorkingGroups/issues/156) in Commonalities to discuss the Subscription/Notification model across all APIs, and security aspects is also something we should probably agree on.

**Comment by akoshunyadi** [comment]
We could also keep the current api-key and add the additional security. Currently the notification content is really not so important, but I'm thinking of future events also in other APIs with sensible data.

**Comment by chrishowell** [comment]
I think mandating all notification recipients implement OAuth flows is a super bad idea, it's way outside the resources that some developers have available to them.

It would be nice to have centralised management of notification servers though, perhaps each having a different set of access credentials, which could be OAuth, or just Bearer. I think this belongs in Commonalities though, rather than QoD.

**Comment by hdamker** [comment]
@chrishowell yes, discussion is happening in Commonalities and everyone is encouraged to support there with reviews and contributions. We will continue here when the guidelines are updated.

**Comment by hdamker** [comment]
This issue is be done, current v0.10.0-rc is following the design guidelines for notifications as defined by Commonalities v0.2.0. If there are additional security requirements by Commonalities we need to open a new issue.
