### ISSUE TITLE
How verification for authorized recipient(eg. UE)  impacts existing QoD API spec

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/QualityOnDemand#8]

**Comment by eric-murray** [comment]
There are three requirements to validate a request to create a session:
1. Identification and authentication of the API caller
2. Identification of the target UE for QoD modification
3. Verification that the API caller is permitted to request QoD modification of the target UE

Requirements (1) is handled by OpenID Connect, which is already specified in the API spec. Requirement (3) is a back office task once the API caller is authenticated and the target UE identified, and does not require additional information to be passed via the API.

For requirement (2), if the API caller is also the UE itself, then this will identify the target UE. If some other entity is calling the API, then the UE must be identified by parameters passed to the API. Currently, only the "ueAddr" & "uePorts" parameter combination can be used for this purpose but, as noted by Ericsson, these may not be known to the API caller if that is not the application server itself.

However, API callers other than the application server should know the UE GPSI (MSDISN). Indeed, this should be the preferred way of identifying the UE, as it is a static identifier.

Vodafone therefore propose:
- It should be possible for the API caller to optionally specify the UE GPSI when creating a session instead the ueAddr / uePorts parameter combination
- Either the GPSI or the ueAddr / uePorts combination must be specified, but not both. This can be achieved using an OAS "oneOf" construct with suitable GPSI and ueAddr/uePorts subschemas. GPSI should be the preferred way of identifying the UE.
- If the API caller is the UE itself, it should pass the GPSI as the identifying parameter even if anyway identified by the OpenID Connect token

**Comment by jordonezlucena** [comment]
@eric-murray _>>It should be possible for the API caller to optionally specify the UE GPSI when creating a session instead the ueAddr / uePorts parameter combination_
What happens when the API caller is the 3rd party (e.g. cloud gaming provider) and the UE has not direct contract with the 3rd party? Is the 3rd party able to gain access to MSISDN/GPSI? Shouldn't operator proceed with the MSISDN/GPSI tokenization, mapping the UE identifier to a token (that is to be issued to the 3rd party as user ID)?

**Comment by Marcin-Jarzab** [comment]
Moved to commonalities and disccused in the "workkgroup".

**Comment by eric-murray** [comment]
This issue was being discussed in parallel in the [Commonalities](https://github.com/camaraproject/WorkingGroups/issues/4) working group. The decision at the last [meeting](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/MeetingMinutes/MOM-2022-05-04.md) was to include this topic within the [Authentication and Authorization Concept for Service APIs](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Working/CAMARA-AuthN-AuthZ-Concept.md) document, which already discusses identifying users (which could be a UE) using OIDC.
